auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki                       # 볼륨에 매핑됨
  storage:
    s3:
      bucketnames: lastdance-s3-bucket
      region: ap-northeast-2
      s3forcepathstyle: true
  ring:
    kvstore: { store: inmemory }
    replication_factor: 1

schema_config:
  configs:
    - from: 2020-01-01                    # 전 기간 v11
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index: { prefix: index_, period: 24h }

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index   # 모두 /loki 내부로
    cache_location: /loki/cache
    resync_interval: 5s
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false        # v11 경고 제거
