auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  storage:
    s3:
      bucketnames: lastdance-s3-bucket
      region: ap-northeast-2
      s3forcepathstyle: true
  ring:
    kvstore: { store: inmemory }
    replication_factor: 1        # Distributor 용

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore: { store: inmemory }
      replication_factor: 1
    num_tokens: 512
    final_sleep: 0s
  chunk_idle_period: 24h       # 하루 단위 업로드 (업무 시간만 업로드)
  chunk_block_size: 4194304    # 4MB로 확대
  chunk_retain_period: 72h     # 청크가 로컬에 유지되는 최대 시간
  max_chunk_age: 24h           # 무조건 하루 단위로 S3 업로드

compactor:
  compaction_interval: 6h      # 기존 10분 → 6시간

schema_config:
  configs:
    - from: 2020-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index: { prefix: index_, period: 24h }

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    resync_interval: 4h          # 기존 5초 → 4시간
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false
  retention_period: 72h        # 3일만 보관 (스토리지 절감)
