auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  storage:
    s3:
      bucketnames: lastdance-s3-bucket
      region: ap-northeast-2
      s3forcepathstyle: true
  ring:
    kvstore: { store: inmemory }
    replication_factor: 1        # Distributor 용

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore: { store: inmemory }
      replication_factor: 1
    num_tokens: 512
    final_sleep: 0s
  chunk_idle_period: 12h      # 청크가 S3에 쓰여지기 전까지 유휴 상태로 유지되는 시간 (9-to-6 환경 최적화)
  chunk_block_size: 262144    # 청크의 블록 크기 (바이트)
  chunk_retain_period: 72h     # 청크가 로컬에 유지되는 최대 시간 (3일로 줄임)
  max_chunk_age: 168h           # 청크가 S3에 쓰여지기 전까지 로컬에 유지되는 최대 시간 (기존 24h에서 7d으로 늘림)

compactor:
  compaction_interval: 10m    # 인덱스 압축 주기

schema_config:
  configs:
    - from: 2020-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index: { prefix: index_, period: 24h }

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    resync_interval: 5s
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false
