spring:
  jpa:
    hibernate:
      ddl-auto: create # 배포 시는 none 또는 validate 추천
    #      ddl-auto: update
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL
        show_sql: true
        format_sql: true
  # 데이터소스
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL
    driver-class-name: org.postgresql.Driver # PostgreSQL
    url: jdbc:postgresql://pg-376d551e-bjy3446-6fda.b.aivencloud.com:20924/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_sNm_l0tQYPIdKL2WpiG

    hikari:
      # 개발 편의성을 위한 설정
      maximum-pool-size: 10         # 여유롭게 10개로 설정
      minimum-idle: 3               # 최소 3개 유지
      connection-timeout: 30000
      idle-timeout: 600000          # 10분
      max-lifetime: 1800000         # 30분

      # 개발 중 디버깅용
      leak-detection-threshold: 180000  # 3분으로 여유롭게