# monitoring/prometheus/prometheus.yml
# Prometheus 설정 파일

global:
  scrape_interval: 30s                # 메트릭 수집 주기
  evaluation_interval: 30s            # 규칙 평가 주기

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] # Alertmanager 서비스 이름

rule_files:
  - "alert.rules"  # 알림 규칙 파일

scrape_configs:
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (호스트 OS 메트릭)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Spring Boot (Blue)
  - job_name: 'spring-boot-blue-app-prod'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['blue-app:8080']

  # Spring Boot (Green)
  - job_name: 'spring-boot-green-app-prod'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['green-app:8081']

  # Grafana 메트릭 (선택 사항)
  - job_name: 'grafana'
    scrape_interval: 60s
    static_configs:
      - targets: ['grafana:3000']

  # Loki 메트릭 (선택 사항)
  - job_name: 'loki'
    scrape_interval: 60s
    static_configs:
      - targets: ['loki:3100']

  # Promtail 메트릭 (선택 사항)
  - job_name: 'promtail'
    scrape_interval: 60s
    static_configs:
      - targets: ['promtail:9080']
